# This is the default config for RoleplayTP by WaRToG
# If you want to put color, simply use minecraft's color code

item:
  type: "PAPER"
  # A custom model data of -1 means the plugin will ignore it
  custom-model-data: -1
  name: "&6Fast Travel"
  description: "&8Used to teleport;&8at a given location"

inventory:
  title: "&6Warps"
  warp-name-color: "&6"
  # between 1 and 6
  # The number of rows also determine the maximum amount of warp
  # Ex: 1 rows = 9 warps
  number-of-rows: 1

messages:
  player-not-online: "&cthis player is not online"
  # You can use {item} and {playerName}
  item-given: "&aYou gave a {item}&a to {playerName}"
  # You can use {item}
  item-received: "&aYou received a {item}"
  no-item-in-hand: "&cYou have no item in your main hand"
  warp-already-exists: "&cThis warp already exists"
  # You can use {warpName}
  warp-set: "&aWarp &6{warpName}&a added"
  warp-does-not-exists: "&cThis warp does not exists"
  # You can use {warpName}
  warp-delete: "&aWarp &6{warpName}&a removed"
  permission: "&cYou don't have permissions to execute this command"
  maximum-amount-warp: "&cYou have already reach the maximum amount of warp"
  # You can use {warpName}
  teleport-to-warp: "&aYou have been teleported to the warp &6{warpName}"